# Assignment 3
## Name : Nooras Fatima Ansari

# Task 1:
### 1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [3]:
def divide(a, b):
    try:
        final = a/b
        print('Division of {} and {} is {}.'.format(a, b, final))
    except ZeroDivisionError:
        print('Division by 0 is not possible !!')

divide(5, 0)

# Division by 0 is not possible !!

Division by 0 is not possible !!


### 2. Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
### Hint: Subject,Verb and Object should be declared in the program as shown below.
#### subjects=["Americans ","Indians"]
#### verbs=["play","watch"]
#### objects=["Baseball","Cricket"]

#### Output should come as below:
- Americans play Baseball.
- Americans play Cricket.
- Americans watch Baseball.
- Americans watch Cricket.
- Indians play Baseball.
- Indians play Cricket.
- Indians watch Baseball.
- Indians watch Cricket.

In [4]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for s in subjects:
    for v in verbs:
        for o in objects:
            print('{} {} {}.'.format(s, v, o))

Americans  play Baseball.
Americans  play Cricket.
Americans  watch Baseball.
Americans  watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


# Task 2:
### 1. Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
### HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.

In [22]:
def powerofrow(x):
    final = []
    for i in x:
        temp = []
        for j in range(len(x)):
            temp.append(i**j)
        final.append(temp) 
    return final

In [23]:
powerofrow([1,2,3,4])

[[1, 1, 1, 1], [1, 2, 4, 8], [1, 3, 9, 27], [1, 4, 16, 64]]

In [26]:
# Reverse
def powerofrow(x):
    final = []
    for i in x:
        temp = []
        for j in range(len(x)):
            temp.append(i**j)
        final.append(temp[::-1]) 
    return final

In [28]:
powerofrow([1,2,3,5])

[[1, 1, 1, 1], [8, 4, 2, 1], [27, 9, 3, 1], [125, 25, 5, 1]]

#### This below solution is from net (copied)

In [29]:
from numpy.core.numeric import (
    asarray, empty, promote_types, multiply
)
def vander(x, N=None, increasing=False):
    """
    Generate a Vandermonde matrix.
    The columns of the output matrix are powers of the input vector. The
    order of the powers is determined by the `increasing` boolean argument.
    Specifically, when `increasing` is False, the `i`-th output column is
    the input vector raised element-wise to the power of ``N - i - 1``. Such
    a matrix with a geometric progression in each row is named for Alexandre-
    Theophile Vandermonde.
    Parameters
    ----------
    x : array_like
        1-D input array.
    N : int, optional
        Number of columns in the output.  If `N` is not specified, a square
        array is returned (``N = len(x)``).
    increasing : bool, optional
        Order of the powers of the columns.  If True, the powers increase
        from left to right, if False (the default) they are reversed.
        .. versionadded:: 1.9.0
    Returns
    -------
    out : ndarray
        Vandermonde matrix.  If `increasing` is False, the first column is
        ``x^(N-1)``, the second ``x^(N-2)`` and so forth. If `increasing` is
        True, the columns are ``x^0, x^1, ..., x^(N-1)``.
    See Also
    --------
    polynomial.polynomial.polyvander
    Examples
    --------
    >>> x = np.array([1, 2, 3, 5])
    >>> N = 3
    >>> np.vander(x, N)
    array([[ 1,  1,  1],
           [ 4,  2,  1],
           [ 9,  3,  1],
           [25,  5,  1]])
    >>> np.column_stack([x**(N-1-i) for i in range(N)])
    array([[ 1,  1,  1],
           [ 4,  2,  1],
           [ 9,  3,  1],
           [25,  5,  1]])
    >>> x = np.array([1, 2, 3, 5])
    >>> np.vander(x)
    array([[  1,   1,   1,   1],
           [  8,   4,   2,   1],
           [ 27,   9,   3,   1],
           [125,  25,   5,   1]])
    >>> np.vander(x, increasing=True)
    array([[  1,   1,   1,   1],
           [  1,   2,   4,   8],
           [  1,   3,   9,  27],
           [  1,   5,  25, 125]])
    The determinant of a square Vandermonde matrix is the product
    of the differences between the values of the input vector:
    >>> np.linalg.det(np.vander(x))
    48.000000000000043 # may vary
    >>> (5-3)*(5-2)*(5-1)*(3-2)*(3-1)*(2-1)
    48
    """
    x = asarray(x)
    if x.ndim != 1:
        raise ValueError("x must be a one-dimensional array or sequence.")
    if N is None:
        N = len(x)

    v = empty((len(x), N), dtype=promote_types(x.dtype, int))
    tmp = v[:, ::-1] if not increasing else v

    if N > 0:
        tmp[:, 0] = 1
    if N > 1:
        tmp[:, 1:] = x[:, None]
        multiply.accumulate(tmp[:, 1:], out=tmp[:, 1:], axis=1)

    return v

In [25]:
vander([1, 2, 3, 5])

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])